version: '3.8'

volumes:
  postgres_data:

services:
  web:
    build: ./server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://pguser:pgpwd@db:5432/pgdb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_DB=pgdb
