version: '3.8'

services:
  web:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True